### ISSUE TITLE
sharing path directories

### ISSUE THREAD

**Issue by valderaplets** [rookie0/nextcloud-sharing-path#14] opened 2020-04-19 08:49 UTC
Hello,

- NC :18.0.3
- sharing-path : 0.2.1

It's okay for file but not for directories ( i don't have the "copy sharing path" with the right click menu :(

**Comment by rookie0** [comment] 2020-04-20 01:28
Yeah, directories can't be accessed, actually is the files under the directory shared that can be accessed.

If you are looking for directory listing, it will not be supported.

**Comment by GlenHuf** [comment] 2020-04-24 20:10
- NC: 18.0.4
- Sharing-path: 0.2.1
The problem is, that even if I share the parent folder, I also have to share each individual file, then I can get and use the sharing path.   I'm not sure this makes sense for a CDN.  It would be so much easier to just share the parent folder and access all files via the sharing path.  The way it is now,  I would have to be constantly checking that each file is shared.  if there were 100's of files and subfolders, that's not very scalable.

**Comment by rookie0** [comment] 2020-04-26 16:03
@GlenHuf Actually you can use it, you can access the file by type the path if the parent folder is shared, just can not get by `Copy Sharing Path`, and i will fix it ASAP.

**Comment by rookie0** [comment] 2020-04-27 07:59
Fixed in [v0.2.2](https://github.com/rookie0/nextcloud-sharing-path/releases/tag/v0.2.2)

**Closed by rookie0** 2020-04-27 07:59 UTC

**Comment by GlenHuf** [comment] 2020-04-27 14:08
Thanks, this is great.  Did you intend the "copy sharing path"  option to be visible for all files?   Now, regardless if the file or folder it's in is shared or not, the option in the right click menu exists.  Thankfully the sharing path link does not work if the file is not shared, but is that by design?   I'm not sure, do you want the option if the link will not actually work?    Maybe that's ok, but either way, this works and is good.  I'm just pointing this out if it's not by design.

**Comment by rookie0** [comment] 2020-04-28 06:35
Yeah, now the `Copy Sharing Path` option are visible for all files, and the design is that the file link can be accessed neither the file is shared or the file parent folder(no matter how many levels) is shared.
