### ISSUE TITLE
Open shared path is a 404 error

### ISSUE THREAD

**Issue by soyohoo** [rookie0/nextcloud-sharing-path#42] opened 2021-12-22 07:54 UTC
In version 22.1.0, the plugin is 0.4.3, 
the shared path is set to: https://nextcloud.host.com/apps/sharingpath/admin, 
and the folder is set to: public/pic.
Open shared path is a 404 error,nginx

![1640159586(1)](https://user-images.githubusercontent.com/53852051/147056110-de80059f-533b-437e-b82d-1a746ac2f099.png)

**Comment by rookie0** [comment] 2022-01-12 08:37
Duplicate of #39.

**Closed by rookie0** 2022-01-12 08:37 UTC

**Comment by oghin7** [comment] 2022-01-20 09:41
In version 23  i   have installed Sharing Path 0.4.3  i got error 404.  can you please tell me the older version may work?
